dist: bionic

before_install:
  - sudo dpkg --add-architecture i386
  
language: java

addons:
  apt:
    update: true
    packages:
      - wine32
      - wine-stable

jdk:
   - openjdk8

branches:
  only:
    - master
    - stable

install: true

script: 
  - (mkdir -p build/wix ; cd build/wix ; curl -SL "http://wixtoolset.org/downloads/v3.9.1006.0/wix39-binaries.zip" -o wix39-binaries.zip ; unzip wix39-binaries.zip; rm -f wix39-binaries.zip)
  - gradle -Dwix_candle=build/wix/candle.exe -Dwix_light=build/wix/light.exe build
  
deploy:
  - provider: script
    skip_cleanup: true
    script: ssh-keyscan -H ftp.interlis.ch >> ~/.ssh/known_hosts; gradle -Drepos_pwd=${repos_pwd} -Drepos_usr=jql_jars-INTE '-Drepos_url=sftp://ftp.interlis.ch' upload
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ssh-keyscan -H ftp.interlis.ch >> ~/.ssh/known_hosts; gradle -Drepos_pwd=${repos_pwd} -Drepos_usr=jql_jars-INTE '-Drepos_url=sftp://ftp.interlis.ch' '-Drelease=' upload
    on:
      branch: stable
