language: java

os: windows

jdk:
  - openjdk8

branches:
  only:
    - master
    - stable

before_install:
- |-  
   choco install wixtoolset --version=3.8.1128.0
   
install: true

  

script: 
  - gradle build 
deploy:
  - provider: script
    skip_cleanup: true
    script: ssh-keyscan -H ftp.interlis.ch >> ~/.ssh/known_hosts; gradle -Drepos_pwd=${repos_pwd} -Drepos_usr=jql_jars-INTE '-Drepos_url=sftp://ftp.interlis.ch' upload
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ssh-keyscan -H ftp.interlis.ch >> ~/.ssh/known_hosts; gradle -Drepos_pwd=${repos_pwd} -Drepos_usr=jql_jars-INTE '-Drepos_url=sftp://ftp.interlis.ch' '-Drelease=' upload
    on:
      branch: stable
